# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "soca"
  s.version = "0.3.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Aaron Quint"]
  s.date = "2012-08-13"
  s.description = "soca is a different way of writing apps for CouchDB. The structure is up to you."
  s.email = "aaron@quirkey.com"
  s.executables = ["soca"]
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "HISTORY",
    "LICENSE",
    "README.md",
    "Rakefile",
    "bin/soca",
    "lib/soca.rb",
    "lib/soca/cli.rb",
    "lib/soca/plugin.rb",
    "lib/soca/plugins/coffeescript.rb",
    "lib/soca/plugins/compass.rb",
    "lib/soca/plugins/credentials.rb",
    "lib/soca/plugins/haml.rb",
    "lib/soca/plugins/jim.rb",
    "lib/soca/plugins/macro.rb",
    "lib/soca/plugins/mustache.rb",
    "lib/soca/pusher.rb",
    "lib/soca/templates/Jimfile",
    "lib/soca/templates/config.js.erb",
    "lib/soca/templates/couchapprc.erb",
    "lib/soca/templates/css/screen.css",
    "lib/soca/templates/db/views/by_type/map.js",
    "lib/soca/templates/hooks/before_build.rb",
    "lib/soca/templates/index.html.erb",
    "lib/soca/templates/js/app.js",
    "lib/soca/templates/js/vendor/jquery-1.7.1.js",
    "lib/soca/templates/js/vendor/jquery.couch-0.11.js",
    "lib/soca/templates/js/vendor/sammy-0.7.1.js",
    "lib/soca/templates/js/vendor/sammy.couch-0.1.0.js",
    "lib/soca/templates/js/vendor/sha1.js",
    "lib/soca/templates/rewrites.js.erb",
    "soca.gemspec",
    "test/helper.rb",
    "test/test_compass_plugin.rb",
    "test/test_credentials_plugin.rb",
    "test/test_macro_plugin.rb",
    "test/test_soca_cli.rb",
    "test/test_soca_pusher.rb",
    "test/testapp/.couchapprc",
    "test/testapp/Jimfile",
    "test/testapp/config.js",
    "test/testapp/css/app.css",
    "test/testapp/db/views/only_map/map.js",
    "test/testapp/db/views/recent/map.js",
    "test/testapp/db/views/recent/reduce.js",
    "test/testapp/hooks/before_build.rb",
    "test/testapp/hooks/before_push.rb",
    "test/testapp/index.html",
    "test/testapp/js/app.js",
    "test/testapp/js/default.js",
    "test/testapp/js/vendor/jquery-1.4.2.js",
    "test/testapp/js/vendor/json2.js",
    "test/testapp/js/vendor/sammy-0.5.4.js",
    "test/testapp/js/vendor/sammy.mustache-0.5.4.js",
    "test/testapp/rewrites.js",
    "test/testapp/templates/index.mustache"
  ]
  s.homepage = "http://github.com/quirkey/soca"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "Sammy on CouchApp"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<json>, ["~> 1.4.6"])
      s.add_runtime_dependency(%q<mime-types>, ["~> 1.16"])
      s.add_runtime_dependency(%q<typhoeus>, ["~> 0.2.4"])
      s.add_runtime_dependency(%q<thor>, ["~> 0.15"])
      s.add_runtime_dependency(%q<jim>, ["~> 0.3"])
      s.add_runtime_dependency(%q<compass>, ["~> 0.11"])
      s.add_runtime_dependency(%q<mustache>, ["~> 0.99"])
      s.add_runtime_dependency(%q<coffee-script>, ["~> 2.2"])
      s.add_development_dependency(%q<rake>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
    else
      s.add_dependency(%q<json>, ["~> 1.4.6"])
      s.add_dependency(%q<mime-types>, ["~> 1.16"])
      s.add_dependency(%q<typhoeus>, ["~> 0.2.4"])
      s.add_dependency(%q<thor>, ["~> 0.15"])
      s.add_dependency(%q<jim>, ["~> 0.3"])
      s.add_dependency(%q<compass>, ["~> 0.11"])
      s.add_dependency(%q<mustache>, ["~> 0.99"])
      s.add_dependency(%q<coffee-script>, ["~> 2.2"])
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
    end
  else
    s.add_dependency(%q<json>, ["~> 1.4.6"])
    s.add_dependency(%q<mime-types>, ["~> 1.16"])
    s.add_dependency(%q<typhoeus>, ["~> 0.2.4"])
    s.add_dependency(%q<thor>, ["~> 0.15"])
    s.add_dependency(%q<jim>, ["~> 0.3"])
    s.add_dependency(%q<compass>, ["~> 0.11"])
    s.add_dependency(%q<mustache>, ["~> 0.99"])
    s.add_dependency(%q<coffee-script>, ["~> 2.2"])
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
  end
end

